FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY dashboard.py ./
COPY d2c_priority.csv ./
COPY spd_priority.csv ./
COPY ltl_priority.csv ./
CMD ["python", "dashboard.py"]
